[package]
name = "vdev"
version = "0.1.0"
edition = "2021"
authors = ["Vector Contributors <vector@datadoghq.com>"]
license = "MPL-2.0"
readme = "README.md"
publish = false

[dependencies]
anyhow = "1.0.71"
atty = "0.2.14"
cached = "0.44.0"
chrono = { version = "0.4.22", default-features = false, features = ["serde", "clock"] }
clap = { version = "4.1.14", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
clap_complete = "4.3.1"
confy = "0.5.1"
directories = "5.0.1"
# remove this when stabilized https://doc.rust-lang.org/stable/std/path/fn.absolute.html
dunce = "1.0.4"
glob = { version = "0.3.1", default-features = false }
hex = "0.4.3"
indexmap = { version = "1.9", default-features = false, features = ["serde"] }
indicatif = { version = "0.17.5", features = ["improved_unicode"] }
itertools = "0.10.5"
log = "0.4.19"
once_cell = "1.18"
os_info = { version = "3.7.0", default-features = false }
# watch https://github.com/epage/anstyle for official interop with Clap
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
paste = "1.0.12"
regex = { version = "1.8.4", default-features = false, features = ["std", "perf"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
sha2 = "0.10.6"
tempfile = "3.6.0"
toml = { version = "0.7.4", default-features = false, features = ["parse"] }
