name: CLI - Linux

on:
  workflow_call:

jobs:
  test-cli:
    runs-on: [linux, ubuntu-20.04-8core]
    env:
      CARGO_INCREMENTAL: 0
    steps:

      # Find the branch that the comment was made in.
      - name: (PR comment) Get PR branch
        if: ${{ github.event_name == 'issue_comment' }}
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      # Indicate in the PR's CI pane that this job is running.
      - name: (PR comment) Set latest commit status as pending
        if: ${{ github.event_name == 'issue_comment' }}
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          context: CLI - Linux
          status: pending

      # Checkout the branch, using the PR ref.
      - name: (PR comment) Checkout PR branch
        if: ${{ github.event_name == 'issue_comment' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      # Checkout the default branch otherwise.
      - name: Checkout branch
        if: ${{ github.event_name != 'issue_comment' }}
        uses: actions/checkout@v3

      - name: Cache Cargo registry + index
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: mock
        run: echo "OK"

      # - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      # - run: bash scripts/environment/prepare.sh
      # - run: echo "::add-matcher::.github/matchers/rust.json"
      # - run: make test-cli
      # - name: Upload test results
      #   run: scripts/upload-test-results.sh
      #   if: always()

      # Indicate in the PR's CI pane that this job is complete
      - name: (PR comment) Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always() && github.event_name == 'issue_comment'
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          context: CLI - Linux
          status: ${{ job.status }}
