name: Cross

on:
  workflow_call:
  issue_comment:
    types: [created]

env:
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"
  CONTAINER_TOOL: "docker"
  DD_ENV: "ci"
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  RUST_BACKTRACE: full
  TEST_LOG: vector=debug
  VERBOSE: true
  CI: true
  PROFILE: debug
  # observing issues fetching boringssl via HTTPS in the OSX build, seeing if this helps
  # can be removed when we switch back to the upstream openssl-sys crate
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  cross-linux:
    name: Cross - ${{ matrix.target }}
    runs-on: [linux, ubuntu-20.04-8core]
    if: |
      !github.event.pull_request
      || github.event.issue.pull_request && contains(github.event.payload.comment.body, '/ci-deploy-cross')
    env:
      CARGO_INCREMENTAL: 0
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: Cache Cargo registry + index
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: 'cargo install cross --version 0.2.4 --force --locked'
      # Why is this build, not check? Because we need to make sure the linking phase works.
      # aarch64 and musl in particular are notoriously hard to link.
      # While it may be tempting to slot a `check` in here for quickness, please don't.
      - run: make cross-build-${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: "vector-debug-${{ matrix.target }}"
          path: "./target/${{ matrix.target }}/debug/vector"

  cross-linux-check:
    name: Cross - Linux
    runs-on: ubuntu-20.04
    needs: cross-linux
    steps:
      - name: Check cross matrix status
        if: ${{ needs.cross-linux.result != 'success' }}
        run: exit 1
