name: Unit - Windows

on:
  workflow_call:
  issue_comment:
    types: [created]

env:
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"
  CONTAINER_TOOL: "docker"
  DD_ENV: "ci"
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  RUST_BACKTRACE: full
  TEST_LOG: vector=debug
  VERBOSE: true
  CI: true
  PROFILE: debug
  # observing issues fetching boringssl via HTTPS in the OSX build, seeing if this helps
  # can be removed when we switch back to the upstream openssl-sys crate
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:

  test-windows:
    runs-on: [windows, windows-2019-8core]
    if: |
      !github.event.pull_request
        || github.event.issue.pull_request && contains(github.event.payload.comment.body, '/ci-deploy-unit-windows')
    steps:
      - uses: actions/checkout@v3
      - run: .\scripts\environment\bootstrap-windows-2019.ps1
      - run: make test
